ValidateReadme: fix bug in reporting
(cherry picked from commit 9b27749c625cabd88bad1bc0e22acfc280a1b772)

diff --git a/.github/workflows/ValidateReadme.yml b/.github/workflows/ValidateReadme.yml
--- a/.github/workflows/ValidateReadme.yml
+++ b/.github/workflows/ValidateReadme.yml
@@ -50,7 +50,7 @@ jobs:
           echo $out
           echo "== DEBUG =="
 
-          errors="$(printf '%s\n' "$out" | grep '^ERROR:' || true)"
+          errors="$(printf '%s\n' "$out" | grep 'ERROR:' || true)"
           [ -n "$errors" ] || errors="None"
 
           {
